<?php

require_once dirname(__FILE__) . '/../../classes/class.ChainUtils.php';

/**
 * Test class for ChainUtils.
 * Generated by PHPUnit on 2011-12-04 at 07:14:15.
 */
class ChainUtilsTest extends PHPUnit_Framework_TestCase {
    protected function setUp() {

    }

    public function testCanExtractOrder1() {
        $callChain = new CallChain();
        $callChain->push("Properties", array("order:title:DESC"));
        $order = ChainUtils::extractOrder($callChain);
        $this->assertNotEmpty($order);
        $this->assertEquals("title", $order[0]['column']);
        $this->assertEquals("DESC", $order[0]['value']);
    }

    public function testCanExtractOrder2() {
        $callChain = new CallChain();
        $callChain->push("Properties", array("order:title:DESC"));
        $callChain->push("tags", array("order:pub_date:ASC"));
        $callChain->orderByOwnership();

        $order = ChainUtils::extractOrder($callChain);
        $this->assertNotEmpty($order);
        $this->assertEquals("pub_date", $order[0]['column']);
        $this->assertEquals("ASC", $order[0]['value']);
        $this->assertEquals("title", $order[1]['column']);
        $this->assertEquals("DESC", $order[1]['value']);
    }

    public function testCanDetectDuplicateTables() {
        $callChain = new CallChain();

        $callChain->push("properties", array("order:title:DESC"));
        $callChain->push("tags", array("order:pub_date:ASC"));
        $callChain->push("properties", array("order:pub_date:ASC"));

        $callChain->orderByOwnership();

        $order = ChainUtils::extractOrder($callChain);
        
    }

    public function testExtractSelectColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testExtractJoins() {

    }

    public function testExtractConditions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
