<?php

require_once dirname(__FILE__) . '/../../classes/class.DebugUtils.php';

/**
 * Test class for DebugUtils.
 * Generated by PHPUnit on 2011-12-04 at 08:36:44.
 */
class DebugUtilsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DebugUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetChain().
     */
    public function testCanGetCallChainInfo() {
        $this->markTestIncomplete();
    }

    public function testCanGetNodeCallChainInfo() {
        $this->markTestIncomplete();
    }
}

?>
